### ISSUE TITLE
Mixtral chat not working. Error: Failed to establish websocket connection.

### ISSUE THREAD

**Issue by miltonmolina** [chathub-dev/chathub#1063]
Getting the following error while using Mixtral chat: Failed to establish websocket connection.

 - OS: [Windows]
 - Browser [Edge]
 - ChatHub Version [v2.3.0]

**Comment by yookibooki** [comment]
Same with Vicuna, Falcon,WizardLM, ChatGLM3 and Yi-Chat

**Comment by DRYN07** [comment]
I got this with every chatbot based on lmsys.org, not just in chathub.gg however I did not find any solution yet.

**Comment by miltonmolina** [comment]
It’s not working even on the latest update. Please fix it!Regards,Milton Sent from my iPhoneOn Feb 14, 2024, at 9:44 AM, DRYN07 ***@***.***> wrote:﻿
I got this with every chatbot based on lmsys.org, not just in chathub.gg however I did not find any solution yet.

**Comment by allentown521** [comment]
same with me

**Comment by wong2** [comment]
I'm working on this.

**Comment by wong2** [comment]
This should be fixed by v2.8.0. Please upgrade.

**Comment by allentown521** [comment]
upgraded to 2.8 still failed for me:
![image](https://github.com/chathub-dev/chathub/assets/69662387/0f2368a4-5dde-4515-9aab-8c838cf83350)

**Comment by wong2** [comment]
Please open https://chat.lmsys.org once, and try agin.

**Comment by allentown521** [comment]
I access the https://chat.lmsys.org/config directly in the browser and return 200 after passing the challenge, it seems that the program needs to handle the situation

**Comment by wong2** [comment]
@allentown521 Yes, I will implement this.

**Comment by wong2** [comment]
v2.8.1 released
